# Site settings
title: "Love2D Open Book"
description: "A free comprehensive guide to game development with Löve2D framework. Learn Lua programming, graphics, physics, and create amazing 2D games."
baseurl: "/love2d-book" # the subpath of your site
url: "https://tianmatics.github.io" # GitHub Pages URL (without the repo name)

# Author information
author: "Limon Das"
github_username: tianmatics
email: tianmatics@gmail.com

# SEO Settings
lang: en_US
timezone: Asia/Dhaka # Add your timezone

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: true
  path: feed.xml

# Social Media
social:
  name: Limon Das
  links:
    - https://github.com/tianmatics
    - https://tianmatics.itch.io
    - mailto:tianmatics@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name/
    sort_by: order

# Page defaults
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"
      author: "Limon Das"
      image: "/assets/images/love2d-default.jpg" # Add a default image
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # Uses page.html layout
      author: "Limon Das"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO tag settings
logo: "/assets/images/love2d-logo.png" # Add your logo
twitter:
  username: tianmatics # Add if you have Twitter
  card: summary_large_image

# Sass settings (optional)
sass:
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - readme.md
  - README.md
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
