title: "Love2D Open Book"
description: "A free book on game development with Löve2D"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tianmatics.github.io/love2d-book" #GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# Markdown settings
defaults:
  layout: default
